name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          role: ci-secret-role
          method: jwt
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t    vault-action-exampleapp
