name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          tlsSkipVerify: true
          role: ci-secret-role
          method: jwt
          path: jwtgh
          namespace: admin
          outputToken: true
          secrets: |
            secret/data/ci app_secret
      - name: Import AppRole roleid
        id: roleid
        run: |
          roleid=$(curl \
          --header "X-Vault-Token: '${{ steps.secrets.outputs.vault_token }}'" \
          --header "X-Vault-Namespace: admin" \
          ${{ secrets.VAULT_ADDR }}/v1/auth/approle/role/vault-actions-exampleapp-prod/role-id); echo "roleid=$roleid" >> $GITHUB_OUTPUT
      - name: Build Docker Image
        run: docker build . --file vault-github-action/Dockerfile --build-arg app_secret="${{ steps.roleid.outputs.roleid }}" -t    vault-action-exampleapp
