name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push


on: [pull_request]

jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: ${{ secrets.your-checkout-token }}
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          tlsSkipVerify: true
          role: ci-secret-role
          method: jwt
          path: jwtgh
          secrets: |
            secret/data/ci app_secret
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t    vault-action-exampleapp
