name: ImageBuilder
# Run this workflow every time a new commit pushed to your repository
on: push

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          tlsSkipVerify: true
          role: ci-secret-role
          method: jwt
          path: jwtgh
          namespace: admin
          exportToken: true
          outputToken: true
          secrets: |
            secret/data/ci app_secret
      - name: Import Wrapping Token
        id: wrappedtoken
        run: |
          token=$(curl \
          --header "X-Vault-Wrap-TTL: 300" \
          --header "X-Vault-Token: ${{ steps.secrets.outputs.vault_token }}" \
          --header "X-Vault-Namespace: admin" \
          --request POST \
          ${{ secrets.VAULT_ADDR }}/v1/auth/approle/role/vault-actions-exampleapp-prod/secret-id); echo "token=$token" >> $GITHUB_OUTPUT
      - name: Build Docker Image
        run: docker build . --file vault-github-action/Dockerfile --build-arg app_secret="${{ steps.wrappedtoken.outputs.token }}" -t    vault-action-exampleapp
